on:
    pull_request:
    push:
        branches:
          - main
    workflow_dispatch:

jobs:
    test:
        name: Run tests
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.8", "3.12"]
                include:
                    - os: macos-latest
                      python-version: "3.9"
        runs-on: ${{matrix.os}}
        steps:
            - id: step1
              run: echo "myvar=42" >> $GITHUB_ENV
            - run: echo ${{steps.step1.outputs.myvar }}
            - run: echo ${{ env.myvar }}
            - uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}
            - if: runner.os == 'Linux'
              run: echo "This is linux"
            - run: python -m pip install .[test]
            - name: Run test
              run: python -m pytest


    deploy:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        needs: test
        steps:
          - run: echo "deploy jobs"

    webslides:
        name: Publish slides
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v3
              with:
                python-version: "3.12"
            - run: python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git
            - name: Generate slides
              run: mdslides slides.md --output_dir slides
            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./slides


    publish_slides:
        needs: webslides

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            - name: Deploy yo
              id: deployment
              uses: actions/deploy-pages@v4





