on:
    pull_request:
    push:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - run: python -m pip install .[test]
            - name: Run test
              run: python -m pytest

